Pipeline
        {
          agent any
          stages
                {
                   stage("Git")
                              {
                               git "https://github.com/Ruchita68/feb-26.git"
                              }
                               stage("Run")
                                           {
                                            sh "python3 main.py"
                                            sh "java Demo.java"
                                           }
               }
        }
